// Shared Tailwind configuration — included in all pages before tailwind CDN
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                 "#f6fafe",
        "tertiary-fixed":             "#85f8c4",
        "surface-tint":               "#49607c",
        "on-primary-fixed-variant":   "#314863",
        "surface-dim":                "#d6dade",
        "on-secondary-container":     "#45627e",
        "on-tertiary-fixed-variant":  "#005137",
        "on-surface-variant":         "#43474d",
        "on-tertiary-container":      "#24a375",
        "surface-container-low":      "#f0f4f8",
        "primary-container":          "#102a43",
        "primary-fixed":              "#d1e4ff",
        "surface-variant":            "#dfe3e7",
        "inverse-primary":            "#b0c9e8",
        "secondary-fixed":            "#cee5ff",
        "surface-bright":             "#f6fafe",
        "error":                      "#ba1a1a",
        "on-secondary-fixed-variant": "#2c4964",
        "on-surface":                 "#171c1f",
        "surface-container-lowest":   "#ffffff",
        "tertiary-fixed-dim":         "#68dba9",
        "secondary-fixed-dim":        "#accaea",
        "error-container":            "#ffdad6",
        "on-primary-fixed":           "#011d35",
        "secondary-container":        "#bfddfe",
        "inverse-on-surface":         "#edf1f5",
        "tertiary-container":         "#00301f",
        "on-error":                   "#ffffff",
        "tertiary":                   "#00190e",
        "surface-container-high":     "#e4e9ed",
        "primary-fixed-dim":          "#b0c9e8",
        "surface-container-highest":  "#dfe3e7",
        "surface":                    "#f6fafe",
        "inverse-surface":            "#2c3134",
        "on-tertiary":                "#ffffff",
        "on-primary-container":       "#7a92b0",
        "secondary":                  "#44617d",
        "on-secondary":               "#ffffff",
        "on-primary":                 "#ffffff",
        "outline-variant":            "#c3c6ce",
        "outline":                    "#74777e",
        "surface-container":          "#eaeef2",
        "on-error-container":         "#93000a",
        "on-secondary-fixed":         "#001d33",
        "on-background":              "#171c1f",
        "primary":                    "#102A43",
        "on-tertiary-fixed":          "#002114",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body":     ["Manrope", "sans-serif"],
        "label":    ["Manrope", "sans-serif"],
        "brand":    ["Playfair Display", "serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "full":    "0.75rem",
      },
    },
  },
};
